### ISSUE TITLE
Push latest version to rubygems.org

### ISSUE THREAD

**Issue by guss77** [ko1/debugger2#7]
Hi guys, any chance to get the latest (1.3.3) version on rubygems.org ?

**Comment by amatsuda** [comment]
@guss77 Are you sure you're requesting a "debugger2" release?

**Comment by guss77** [comment]
I'm looking at this: https://rubygems.org/gems/debugger2 , which I understand to be this project, though the rubygems artifact is 1.0 beta while this repo purports to be version 1.3.3

I'm not sure what its used for, but I'm running operations for a company where we're using it and we're trying to move away from deployments from github (using bundler) to gems repo only. Currently we consume the gem "debugger2" from this repository. Is there any reason for me not to request a debugger2 release?

**Comment by amatsuda** [comment]
Ah! I think I got what you mean. You found "version 1.3.3" in the CHANGELOG, right? Is there anywhere else you see 1.3.3?

**Comment by guss77** [comment]
well, the commit message for that file. I also saw that the last commit on the repo was later than the last publish date on the gem, but now I see that it was just a readme change. 

So, no worries for now, but it might be a good idea to have the documentation agree with the code ;-)

**Comment by amatsuda** [comment]
@guss77 Good point. Thanks for your advice :)
